sequenceDiagram
    participant browser
    participant server

    Note right of browser: User writes input and clicks Save button
    Note right of browser: Browser invokes form onsubmit function that adds new note to the list and sends note to server as json
    browser ->> server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa {"content":"new note","date":"2025-11-26T00:17:23.946Z"}
    activate server
    server -->> browser: 201 Created {"message":"note created"}
    deactivate server
    